In [1]:
import os
import numpy as np
from tensorflow import keras
from pyrsgis import raster
from pyrsgis.convert import changeDimension
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score

In [19]:
mxBangalore = r"C:\Users\harsh\Desktop\LCC-U-NN\l5_Bangalore2011_raw.tif"
builtupBangalore = r"C:\Users\harsh\Desktop\LCC-U-NN\l5_Bangalore2011_builtup.tif"
Shillong = r"C:\Users\harsh\Desktop\LCC-U-NN\Delhi_L5_B1to7.tif"

In [20]:
ds1, featuresBangalore = raster.read(mxBangalore, bands='all')
ds2, labelBangalore = raster.read(builtupBangalore, bands=1)
ds3, Shillong_data  = raster.read(Shillong , bands='all')

In [21]:
np.unique(Shillong_data)

array([ 10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5,
        15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,
        19.5,  20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,  23.5,
        24. ,  24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,  28. ,
        28.5,  29. ,  29.5,  30. ,  30.5,  31. ,  31.5,  32. ,  32.5,
        33. ,  33.5,  34. ,  34.5,  35. ,  35.5,  36. ,  36.5,  37. ,
        37.5,  38. ,  38.5,  39. ,  39.5,  40. ,  40.5,  41. ,  41.5,
        42. ,  42.5,  43. ,  43.5,  44. ,  44.5,  45. ,  45.5,  46. ,
        46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5,  50. ,  50.5,
        51. ,  51.5,  52. ,  52.5,  53. ,  53.5,  54. ,  54.5,  55. ,
        55.5,  56. ,  56.5,  57. ,  57.5,  58. ,  58.5,  59. ,  59.5,
        60. ,  60.5,  61. ,  61.5,  62. ,  62.5,  63. ,  63.5,  64. ,
        64.5,  65. ,  65.5,  66. ,  66.5,  67. ,  67.5,  68. ,  68.5,
        69. ,  69.5,  70. ,  70.5,  71. ,  71.5,  72. ,  72.5,  73. ,
        73.5,  74. ,

In [22]:
Shillong_data.dtype

dtype('float64')

In [23]:
featuresBangalore.dtype

dtype('float32')

In [24]:
print(featuresBangalore)

[[[ 30.  30.  30. ...  27.  26.  25.]
  [ 30.  29.  29. ...  26.  25.  25.]
  [ 32.  31.  28. ...  25.  25.  25.]
  ...
  [ 36.  36.  37. ...  30.  31.  30.]
  [ 36.  37.  37. ...  29.  30.  29.]
  [ 32.  33.  35. ...  28.  29.  29.]]

 [[ 28.  31.  31. ...  28.  28.  26.]
  [ 30.  28.  28. ...  27.  27.  28.]
  [ 35.  34.  27. ...  26.  25.  26.]
  ...
  [ 46.  49.  50. ...  32.  35.  34.]
  [ 49.  52.  52. ...  30.  32.  31.]
  [ 41.  43.  47. ...  29.  30.  31.]]

 [[ 70.  67.  63. ...  62.  62.  61.]
  [ 61.  69.  66. ...  61.  60.  62.]
  [ 65.  64.  66. ...  60.  58.  59.]
  ...
  [ 67.  69.  68. ...  58.  59.  60.]
  [ 69.  67.  65. ...  57.  57.  58.]
  [ 56.  57.  62. ...  55.  57.  59.]]

 [[ 77.  74.  80. ...  91.  89.  74.]
  [ 80.  77.  75. ...  83.  83.  80.]
  [ 82.  84.  74. ...  82.  82.  85.]
  ...
  [117. 120. 124. ...  86.  95. 102.]
  [115. 119. 127. ...  81.  87.  93.]
  [102.  97. 110. ...  88.  91.  94.]]

 [[140. 139. 138. ... 143. 143. 142.]
  [139. 138. 138. 

In [25]:
print("Bangalore multispectral image shape: ", featuresBangalore.shape)
print("Bangalore binary built-up image shape: ", labelBangalore.shape)
print("Guwahati multispectral image shape: ", Shillong_data.shape)

Bangalore multispectral image shape:  (6, 2054, 2044)
Bangalore binary built-up image shape:  (2054, 2044)
Guwahati multispectral image shape:  (6, 228, 313)


In [26]:
featuresBangalore = changeDimension(featuresBangalore)
labelBangalore = changeDimension (labelBangalore)
Shillong_data = changeDimension(Shillong_data)
nBands = featuresBangalore.shape[1]
labelBangalore = (labelBangalore == 1).astype(int)

The "changeDimension()" function has moved to "array_to_table()" and will be deprecated in future versions. Please check the pyrsgis documentation at https://pyrsgis.readthedocs.io/en/master/ for more details.
The "changeDimension()" function has moved to "array_to_table()" and will be deprecated in future versions. Please check the pyrsgis documentation at https://pyrsgis.readthedocs.io/en/master/ for more details.
The "changeDimension()" function has moved to "array_to_table()" and will be deprecated in future versions. Please check the pyrsgis documentation at https://pyrsgis.readthedocs.io/en/master/ for more details.


In [27]:
print("Bangalore multispectral image shape: ", featuresBangalore.shape)
print("Bangalore binary built-up image shape: ", labelBangalore.shape)
print("Hyderabad multispectral image shape: ", Shillong_data.shape)

Bangalore multispectral image shape:  (4198376, 6)
Bangalore binary built-up image shape:  (4198376,)
Hyderabad multispectral image shape:  (71364, 6)


In [31]:
xTrain, xTest, yTrain, yTest = train_test_split(featuresBangalore, labelBangalore, test_size=0.4, random_state=42)

print(xTrain.shape)
print(yTrain.shape)

print(xTest.shape)
print(yTest.shape)

(2519025, 6)
(2519025,)
(1679351, 6)
(1679351,)


In [32]:

xTrain = xTrain / 255.0
xTest = xTest / 255.0
Shillong_data = Shillong_data/ 182.0


xTrain = xTrain.reshape((xTrain.shape[0], 1, xTrain.shape[1]))
xTest = xTest.reshape((xTest.shape[0], 1, xTest.shape[1]))
Assam_data = Shillong_data.reshape((Shillong_data.shape[0], 1, Shillong_data.shape[1]))


print(xTrain.shape, xTest.shape, Shillong_data.shape)

(2519025, 1, 6) (1679351, 1, 6) (71364, 6)


In [33]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(1, nBands)),
    keras.layers.Dense(14, activation='relu'),
    keras.layers.Dense(2, activation='softmax')])

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])


model.fit(xTrain, yTrain, epochs=2)

Epoch 1/2
78720/78720 [==============================] - 70s 878us/step - loss: 0.1245 - accuracy: 0.9533
Epoch 2/2
78720/78720 [==============================] - 77s 979us/step - loss: 0.1081 - accuracy: 0.9591


In [15]:
yTestPredicted = model.predict(xTest)
yTestPredicted = yTestPredicted[:,1]

52480/52480 [==============================] - 38s 728us/step


In [34]:
yTestPredicted = (yTestPredicted>0.5).astype(int)
cMatrix = confusion_matrix(yTest, yTestPredicted)
pScore = precision_score(yTest, yTestPredicted)
rScore = recall_score(yTest, yTestPredicted)

print("Confusion matrix: for 14 nodes\n", cMatrix)
print("\nP-Score: %.3f, R-Score: %.3f" % (pScore, rScore))

Confusion matrix: for 14 nodes
 [[1454336   26540]
 [  41871  156604]]

P-Score: 0.855, R-Score: 0.789


In [35]:
predicted = model.predict(Assam_data)
predicted = predicted[:,1]

2231/2231 [==============================] - 1s 585us/step


In [36]:
prediction = np.reshape(predicted, (ds3.RasterYSize, ds3.RasterXSize))
outFile = 'Delhi_2011_BuiltupNN_predicted.tif'
raster.export(prediction, ds3, filename=outFile, dtype='float')